language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: 
  -"pip install -i http://packages.astro.pic.es/simple/ brownthrower"
  - "python setup.py install"
# command to run tests

script: nosetests
