language: python
python:
  - "2.6"
  - "2.7"

# command to install dependencies
install: 
  - "pip install -i http://packages.astro.pic.es/simple/ brownthrower"
  - "python setup.py install"
  - "sudo npm install -g karma"
# command to run tests

script: 
   - nosetests
   - karma start client/config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox

