language: node_js
node_js:
  - 0.10

# command to install dependencies
install: 
  - "sudo easy_install virtualenv"
  - "virtualenv prova"
  - "source prova/bin/activate"
  - "pip install -i http://packages.astro.pic.es/simple/ brownthrower"
  - "python setup.py install"
  - "npm install -g karma"
  - "cd client"
  - "npm install"
  - "cd .."
# command to run tests

script: 
   - nosetests
   - cd client
   - ./scripts/test.sh

