language: node_js
node_js:
  - 0.10

# command to install dependencies
install: 
  - "virtualenv prova"
  - "source prova/bin/activate"
  - "pip install -i http://packages.astro.pic.es/simple/ brownthrower"
  - "python setup.py install"
  - "npm install -g karma"
# command to run tests

script: 
   - nosetests
   - karma start client/config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox

